POST http://localhost:3001/api/blogs
Content-Type: application/json
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJvb3QiLCJpZCI6IjVmMDgwYjlkOTZiZDQ0MDIyMGY2MjZmYSIsImlhdCI6MTU5NDM2MzM5OX0.LhAlRz6xdC_xH_hA_tMDOlnjVxZ1mUe4JOkdogoj20o

{
  "title": "7.X written by root",
  "author": "root",
  "url": "google.com",
  "likes": "13",
  "userId": "5f080b9d96bd440220f626fa"
}